print('this is a test for git push')
print('Adde a second test line')
print('Added for quicktest')
print('Added 4th line in master branch')
print('Added as part of test_quick)')
print('Added line 2 as part of test_quick')
print('Added line 3 as part of test_quick')
print('Added line 4 as part of test_quick')
